version: "3.8"
services:
  test:
    container_name: "test"
    depends_on:
      - db
    image: test
    ports:
      - "80:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=123
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test

networks:
  overlay: